![auto_calculus](asset\auto_calculus.png)

In [2]:
import torch
x = torch.tensor([1,2,3,4],dtype=torch.float32)
x.requires_grad_(True)
# 默认值是None
x.grad

In [5]:
y = 2 * torch.dot(x,x)
# 求导
y.backward()
# 打印y对x的导数
print(x.grad)
# 验证正确性
x.grad == 4 * x

# 默认情况下pytorch会累计梯度，需要清除之前的值
x.grad.zero_()

tensor([ 4.,  8., 12., 16.])


tensor([0., 0., 0., 0.])

In [35]:
# 可以将某些计算移到计算图之外
# x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
print(x.grad == u)

tensor([True, True, True, True])


In [37]:
x.grad.zero_()
# 当你调用 .backward() 时，PyTorch 要从一个最终标量开始（比如 loss），然后往前把梯度一层一层传播回去，这就是“标量链式”的运作方式。
y.sum().backward()
print(x.grad == 2*x)

tensor([True, True, True, True])


In [41]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

# 🔹 torch.randn(size=())
# 表示创建一个从标准正态分布（均值为 0，标准差为 1）中随机采样的标量张量（scalar tensor）。
#
# size=() 就是空的 tuple，代表这是一个 0 维张量（即标量）
#
# 它的值是类似 tensor(0.2435) 这样的一个数
#
# 🔹 requires_grad=True
# 告诉 PyTorch：
#
# “我要对这个变量 a 开启梯度追踪（track gradient）。”
#
# 以后你调用 .backward() 时，PyTorch 就会自动计算这个标量 a 对 loss 的导数，保存在 a.grad 中。
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()
a.grad

tensor(4096.)

- 精度下降避免不断测量的最大背景的潜在累积误差
- 小批量随机梯度下降是深度学习训练中的关键算法
- 随机重采样的重要性比量大小和学习率