In [2]:
import torch

# 从0到12（开区间）结束的所有整数组成的向量
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# 向量的形状
x.shape

torch.Size([12])

In [4]:
# 向量中元素的个数
x.numel()

12

In [5]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [6]:
x = torch.tensor([1.0,2,3,4,5])
y = torch.tensor([2,2,2,2,2])
# 按元素的运算
# 倒数第二个是x的y次冥
# 倒数第一个是每个元素的e指数
x+y, x-y, x*y, x/y, x**y, torch.exp(x)

(tensor([3., 4., 5., 6., 7.]),
 tensor([-1.,  0.,  1.,  2.,  3.]),
 tensor([ 2.,  4.,  6.,  8., 10.]),
 tensor([0.5000, 1.0000, 1.5000, 2.0000, 2.5000]),
 tensor([ 1.,  4.,  9., 16., 25.]),
 tensor([  2.7183,   7.3891,  20.0855,  54.5981, 148.4132]))

In [7]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
y = torch.arange(12, dtype=torch.float32).reshape((3,4))
# 其中这里的dim0是列，dim1是行
torch.cat((x,y), dim=0), torch.cat((x,y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[ 0.,  1.,  2.,  3.,  0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.,  4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.,  8.,  9., 10., 11.]]))

In [8]:
# 广播机制，当张量形状不一样的时候会自动扩充
x = torch.arange(3, dtype=torch.float32).reshape((1,3))
y = torch.arange(2, dtype=torch.float32).reshape((2,1))
# 它会把原来的张量给复制成一个最小公倍数的形状，再进行相加
x, y, x+y

(tensor([[0., 1., 2.]]),
 tensor([[0.],
         [1.]]),
 tensor([[0., 1., 2.],
         [1., 2., 3.]]))

In [25]:
x = torch.arange(3, dtype=torch.float32).reshape((1,1,3))
# 通过索引写入指定元素
x[0,0,2] = 9
x

tensor([[[0., 1., 9.]]])

In [29]:
# pycharm对于本地文件的反应有点慢，具体文件生成效果用电脑自带的文件浏览器查看
import os

# 获取当前工作目录
current_directory = os.getcwd()

print("当前工作目录是：", current_directory)

# 创建一个名为"data"的目录，如果目录已存在，则不会抛出错误。
os.makedirs(os.path.join('data'), exist_ok=True)

# 定义CSV文件的路径
data_file = os.path.join('data', 'house_tiny2.csv')

# 使用with语句打开文件，确保文件最后可以正确关闭
with open(data_file, 'w') as f:
    # 写入表头
    f.write('NumRooms,Alley,Price\n')
    # 写入第一行数据
    f.write('NA,Pave,127500\n')
    # 写入第二行数据
    f.write('2,NA,106000\n')
    # 写入第三行数据
    f.write('4,NA,178100\n')
    # 写入第四行数据
    f.write('NA,NA,150000\n')


当前工作目录是： F:\000-CS\pycharm\deep_learning_coding\deep_learning_coding\data
os.path = <module 'ntpath' from 'C:\\Users\\chill\\.conda\\envs\\deep_learning\\Lib\\ntpath.py'>


In [30]:
import pandas as pd
data_file = os.path.join('data', 'housing.csv')
data = pd.read_csv(data_file)
type(data)

pandas.core.frame.DataFrame

In [2]:
# 这其中会遇到的问题包括，数值缺失的处理
# 处理方法一：直接抛弃缺失数据的行
# 处理方法二，对于缺失的数据做一定处理，例如：
import torch
import pandas as pd

# 假设已有data DataFrame的定义
# 创建一个包含浮点数的tensor
data = torch.tensor([
    [1.0, 2.0,1],
    [torch.nan, 3.0,torch.nan],
    [4.0, torch.nan,1]
])
# 将tensor转换为DataFrame
df = pd.DataFrame(data.numpy(), columns=['Feature1', 'Feature2', 'Target'])


# 使用iloc选择DataFrame中的某些部分
# iloc 是 "integer location" 的缩写
inputs, outputs = df.iloc[:, 0:2], df.iloc[:, -1]

# 使用fillna填充缺失值，这里填充的是NumRooms列的均值
inputs = inputs.fillna(inputs.mean())

# 打印inputs DataFrame查看结果
inputs, outputs


(   Feature1  Feature2
 0       1.0       2.0
 1       2.5       3.0
 2       4.0       2.5,
 0    1.0
 1    NaN
 2    1.0
 Name: Target, dtype: float32)

In [34]:
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
# 对第一个维度，即每一列开始求和
torch.sum(x,dim=0)

tensor([12., 15., 18., 21.])

In [14]:
# torch.tensor与numpy之间的相互转换
# tensor->numpy
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
x.numpy()
# numpy->tensor
torch.tensor(x.numpy())

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [36]:
# tensor与标量的相互转换
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [16]:
# 矩阵的转置
a = torch.arange(16, dtype=torch.float32).reshape((4,4))
# 以及判断是否是对称矩阵。如果要比较，他们的形状必须一致
a, a.T, a==a.T

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]),
 tensor([[ 0.,  4.,  8., 12.],
         [ 1.,  5.,  9., 13.],
         [ 2.,  6., 10., 14.],
         [ 3.,  7., 11., 15.]]),
 tensor([[ True, False, False, False],
         [False,  True, False, False],
         [False, False,  True, False],
         [False, False, False,  True]]))

In [17]:
# 关于对象的引用，如果需要重新分配内存，可以使用。clone()
a = torch.arange(16, dtype=torch.float32).reshape((4,4))
b = a.clone()
c = a


In [18]:
# 求和，求平均
x = torch.arange(12, dtype=torch.float32).reshape((3,4))
# keepdim可以留作广播机制
x, x.mean(), x.sum() / x.numel(), x.mean(dim=0), x.mean(dim=0, keepdim=True) , x.sum(dim=0) / x.shape[0]

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor(5.5000),
 tensor(5.5000),
 tensor([4., 5., 6., 7.]),
 tensor([[4., 5., 6., 7.]]),
 tensor([4., 5., 6., 7.]))

In [19]:
# 点积是按元素乘积求和
x = torch.arange(12, dtype=torch.float32)
y = torch.ones(12)
x, y, x.dot(y)

(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.]),
 tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 tensor(66.))

In [38]:
A = torch.arange(20, dtype=torch.float32).reshape((5,4))
x = torch.arange(4, dtype=torch.float32)
B = torch.ones(12, dtype=torch.float32).reshape((4,3))
# matrix-vector, matrix-matrix
A.mv(x), A.mm(B), A@x,  A @ B

(tensor([ 14.,  38.,  62.,  86., 110.]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]),
 tensor([ 14.,  38.,  62.,  86., 110.]),
 tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

In [21]:
# L1范数, Frobenius norm(类似L2 NORM, 平方和的开根号)
A.abs().sum(), torch.norm(A)

(tensor(190.), tensor(49.6991))

In [3]:
from os import environ

import torch
from pandas.conftest import axis_1

# bug fix records:
# error: no module named torch
# first check the conda env in terminal `conda env list`
# then run `python -c "import torch; print(torch.__version__)"` to check if torch installed
# finally go pycharm setting to set the python interpreter to the corresponding env
# and invalidate cache.

x = torch.arange(12,30)
print(f"{x = }")
print(f"{x.shape = }")
# number of element
print(f"{x.numel() = }")
# 改变形状，但不改变元素值
print(f"{x.reshape(3,6) = }")
# 通过索引访问元素
print(f"{x[3] = }")

# 初始化，生成一个指定的形状，内容全为0或者1
print(f"{torch.zeros(2,3,4) = }")
    # dim=0 的大小是 2，意味着在最外层维度上有2个元素。
    # dim=1 的大小是 3，表示第二层维度上每个元素包含3个元素。
    # dim=2 的大小是 4，表示第三层维度上每个元素包含4个元素。
    # dim=3 的大小是 5，表示第四层维度上每个元素包含5个元素。
print(f"{torch.ones(2,3,4,5) = }")
# 初始化，创建指定值的张量
print(f"{torch.tensor([[1,2,3,4],[5,6,7,8]]).shape = }")


ModuleNotFoundError: No module named 'hypothesis'

In [3]:
import numpy
print(numpy.__version__)


2.2.2


![Show Element](./asset/show_element.png "This is an example image")

In [1]:
import torch

# 检查 CUDA 是否可用，并输出当前 CUDA 设备
if torch.cuda.is_available():
    print("CUDA is available. Current device:", torch.cuda.current_device())
    print("CUDA Device name:", torch.cuda.get_device_name(0))
else:
    print("CUDA is not available.")


CUDA is available. Current device: 0
CUDA Device name: NVIDIA GeForce RTX 4090 Laptop GPU


In [2]:
print("hello world")

hello world


In [5]:
# 张量的长度
print(f"{x = }")

# 张量的形状
print(f"{x.reshape(6,3).T.shape = }")
# 矩阵的转置
print(f"{x.reshape(6,3).T = }")

x = tensor([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])
x.reshape(6,3).T.shape = torch.Size([3, 6])
x.reshape(6,3).T = tensor([[12, 15, 18, 21, 24, 27],
        [13, 16, 19, 22, 25, 28],
        [14, 17, 20, 23, 26, 29]])


In [24]:
a = torch.tensor([[1,2,3],
                  [2,1,7],
                  [3,7,1]], dtype=torch.float)
identity_matrix = torch.eye(3)
# 如果一个矩阵是对称矩阵的话，可以做如下判断，所有的值都将是True
# *是将每个对应元素用数学乘法
# @是矩阵乘法
# torch.mv() 中的第i个元素是a的第i行和后面向量的点积
a == a.T, a * identity_matrix, a @ identity_matrix, torch.mv(a,torch.tensor([1,1,1],dtype=torch.float))

(tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]),
 tensor([[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]),
 tensor([[1., 2., 3.],
         [2., 1., 7.],
         [3., 7., 1.]]),
 tensor([ 6., 10., 11.]))

In [21]:
# 求均值，求和
torch.tensor([[1,2,3,4],
              [5,6,7,8]],dtype=float).mean(axis=1)


tensor([2.5000, 6.5000], dtype=torch.float64)

In [25]:
# L2范数
torch.norm(torch.tensor([1,2,3,4],dtype=torch.float))

tensor(5.4772)

In [ ]:
# L1范数：
torch.tensor([1,2,3,4],dtype=torch.float).abs().sum()

<img src="asset\L1.png" alt="L1" width="400" height="400" align="left">

In [28]:
# 矩阵的L2范数， 它相当于是把矩阵拉成一个一维的向量，然后求范数
torch.norm(torch.ones(4,9))

tensor(6.)

In [36]:
a = torch.tensor([[1,2,3,4],[5,6,7,8]])
b = torch.ones(4,9,6,7)
# 对哪个轴求和，哪个轴的维度就会消掉; 但是如果keepdim, 那么对应的轴维度就是1
a.shape, a.sum(axis=0).shape, a.sum(axis=1, keepdim=True), b.sum(axis = 1).shape, b.sum(axis = 2, keepdim = True).shape

(torch.Size([2, 4]),
 torch.Size([4]),
 tensor([[10],
         [26]]),
 torch.Size([4, 6, 7]),
 torch.Size([4, 9, 1, 7]))

In [18]:
# 这样做可以保持维度，广播机制要求唯独一样。广播机制的核心是：当两个张量的形状不同时，PyTorch 会尝试自动扩展（广播）较小的张量，以匹配较大的张量形状，从而使得张量可以进行逐元素操作。
torch.tensor([[1,2,3,4],
              [5,6,7,8]],dtype=float).mean(axis=1,keepdim=True)

tensor([[2.5000],
        [6.5000]], dtype=torch.float64)

In [17]:
x = torch.tensor([1.0,2,3,4,5])
y = torch.tensor([2,2,2,2,2])
x+y, x-y, x*y, x/y, x**y

(tensor([3., 4., 5., 6., 7.]),
 tensor([-1.,  0.,  1.,  2.,  3.]),
 tensor([ 2.,  4.,  6.,  8., 10.]),
 tensor([0.5000, 1.0000, 1.5000, 2.0000, 2.5000]),
 tensor([ 1.,  4.,  9., 16., 25.]))

In [27]:
X = torch.tensor([[1,2,3,4],[5,6,7,8]])
Y = torch.arange(9,17,dtype=torch.float32).reshape(2,4)
# concatenate
torch.cat(tensors=(X,Y),dim=0), torch.cat(tensors=(X,Y),dim=1)


(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 16.]]),
 tensor([[ 1.,  2.,  3.,  4.,  9., 10., 11., 12.],
         [ 5.,  6.,  7.,  8., 13., 14., 15., 16.]]))

In [30]:
X = torch.tensor([[1,2,3,4],[5,6,7,8]])
X[0,2] = 11
X[0,:] = 11
Y = torch.arange(9,17,dtype=torch.float32).reshape(2,4)
# dim 0 是列， dim 1 是行
Y==X, X.sum(dim=1)

(tensor([[False, False,  True, False],
         [False, False, False, False]]),
 tensor([44, 26]))

In [35]:
before = id(Y)
print(f"{before = }")
# 会创建一个新的拷贝
# Y = X+Y

# 会原地处理
Y[:] = X+Y
Y += X
print(f"{(before == id(Y))= }")


before = 2115769103248
(before == id(Y))= True


In [37]:
# 和numpy之间的转换
A = X.numpy()
B = torch.tensor(A)
type(A) , type(B)

NameError: name 'X' is not defined

In [ ]:
# 广播机制：broadcasting mechanism 


In [37]:
# 和标量的转换
a = torch.tensor(3.5)
a, a.item(), float(a), int(a)

(tensor(3.5000), 3.5, 3.5, 3)

In [ ]:
# 求导：



<img src="asset\matrix_calculus.png" alt="L1" width="600" height="600" align="left">

<img src="asset\matrix_calculus_shape.png" alt="L1" width="600" height="600" align="left">

## 计算图：
<img src="asset\computing_graph.png" alt="L1" width="300" height="300" align="left">
<img src="asset\back_propagation.png" alt="L1" width="300" height="300" align="left">


In [2]:
# 求导：
import torch

x = torch.arange(12, dtype=torch.float)
# 通过调用 requires_grad_(True)，这行代码修改张量 x，使其开始追踪对其的所有操作。这是为了之后能够对其进行自动求导（自动微分）。
# 在 PyTorch 中，函数名末尾带有下划线 _ 的函数表示它们会进行 原地操作（in-place operation），即直接修改调用它的对象而不是创建一个新的对象。
x.requires_grad_(True)
# 此时，x.grad 用来查看 x 的梯度。由于我们还没有进行任何计算导致梯度变化（如反向传播），x.grad 应该是 None。x.grad 存储了 x 的梯度，梯度是通过调用 .backward() 方法（执行反向传播时）计算得到的。
x.grad

y = 2 * torch.dot(x,x)
y



tensor(1012., grad_fn=<MulBackward0>)

In [19]:
y.backward()
x.grad


tensor([ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36., 40., 44.])

In [20]:
x.grad == 4*x

tensor([True, True, True, True, True, True, True, True, True, True, True, True])

In [26]:
# 默认情况下pytorch会累计梯度，我们先给它清除掉
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [27]:
# y是非标量的情况(y是向量)：
x.grad.zero_()
y = x*x

# 先对结果y做一个求和，使得结果y是一个标量
y.sum().backward()
x.grad

tensor([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22.])

In [30]:
# detach: 将计算挪到计算图之外
x.grad.zero_()
y = x * x
# detach之后，u相当于是一个常数了，而不是包含x的关系
u = y.detach()
z = u * x

z.sum().backward()
x.grad == u

tensor([True, True, True, True, True, True, True, True, True, True, True, True])

In [ ]:
# 即使计算图需要通过Python的控制流，如循环，条件或者任意函数调用等，我们仍然可以计算得到变量的梯度

# 这就是隐式自动求导比显示求导更方便的地方。

In [ ]:
import random
import torch
from d2l import torch as d2l



配置MSVC到环境变量：
`set PATH=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.42.34433\bin\Hostx86\x86;%PATH%`